behaviors:
  Curriculum:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true

environment_parameters:
  checkpoint_reward:
    curriculum:
      - name: Lesson0
        completion_criteria:
          mesure: reward
          behavior: Curriculum
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 0.7
        value: 0.2
      - name: Lesson1
        completion_criteria:
          mesure: reward
          behavior: Curriculum
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 0.9
        value: 0.05
      - name: Lesson2
        value: 0.02

  episode_reward:
    curriculum:
      - name: Lesson0
        completion_criteria:
          mesure: reward
          behavior: Curriculum
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 0.7
        value: 0.0
      - name: Lesson1
        completion_criteria:
          mesure: reward
          behavior: Curriculum
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 0.9
        value: 0.9
      - name: Lesson2
        value: 2.0

  step_reward:
    curriculum:
      - name: Lesson0
        completion_criteria:
          mesure: reward
          behavior: Curriculum
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 0.7
        value: 0.0
      - name: Lesson1
        completion_criteria:
          mesure: reward
          behavior: Curriculum
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 0.9
        value: 0.0
      - name: Lesson2
        value: -0.002
    
