behaviors:
  Imitation:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:

      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.005
        encoding_size: 64
        learning_rate: 0.0003

      gail:
        gamma: 0.99
        strength: 0.01
        encoding_size: 64
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: Demonstrations/Immitation_0.demo
    keep_checkpoints: 5

    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    behavioral_cloning:
      demo_path: Demonstrations/Immitation_0.demo
      steps: 10000
      strength: 0.5
      samples_per_update: 0

    
